apiVersion: apps/v1
kind: Deployment
metadata:
  name: sa-health-telegram-app
  labels:
    app: sa-health-telegram-app
spec:
  selector:
    matchLabels:
      app: sa-health-telegram-app
  replicas: 1
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: sa-health-telegram-app
    spec:
      containers:
        - image: ghcr.io/romancha/server-healthcheck:latest
          imagePullPolicy: Always
          name: sa-health-telegram-app
          env:
            - name: TELEGRAM_TOKEN
              value: "7646051916:AAETLO4PjCY1hsGv8vBUFhY_oVDFmno4yCs"
            - name: TELEGRAM_CHAT
              value: "451248415"
          volumeMounts:
            - name: data-volume
              mountPath: /data
          command: ["/go/bin/app", "--super=youTelegramUser", "--super=VladLushkov"]
          ports:
            - containerPort: 8080
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: data-pvc