apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-telegram-sender.fullname" . }}
  labels:
    {{- include "k8s-telegram-sender.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      nodePort: 30007
  selector:
    {{- include "k8s-telegram-sender.selectorLabels" . | nindent 4 }}
