apiVersion: v1
kind: Service
metadata:
  name: sa-healthcheck-telegram-app-lb
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      nodePort: 30007
  selector:
    app: sa-health-telegram-app